name: Build, Publish and Deploy

on:
  release:
    types: [published]

env:
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16'
      - name: Build and push Docker image
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_USER: ${{ secrets.GIT_USER }}
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          docker build . --file Dockerfile --tag turistikrota/service.auth:$IMAGE_TAG --build-arg GITHUB_TOKEN=$GIT_TOKEN --build-arg GITHUB_USER=$GIT_USER
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push turistikrota/service.auth:$IMAGE_TAG

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull and run the Docker image on the server
        env:
          DIR: ${{ secrets.DIR }}
          SECRET_NAME_1: ${{ secrets.SECRET_NAME_1 }}
          SECRET_NAME_2: ${{ secrets.SECRET_NAME_2 }}
          NETWORK_NAME: ${{ secrets.NETWORK_NAME }}
          APP_PORT: ${{ secrets.APP_PORT }}
          HOST_ALIAS: ${{ secrets.HOST_ALIAS }}
          REDIS_HOST_ALIAS: ${{ secrets.REDIS_HOST_ALIAS }}
          HOST_IP: ${{ secrets.HOST_IP }}
        run: |
          docker service ls | grep -q service-auth && docker service rm service-auth || true
          cd $DIR
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker pull turistikrota/service.auth:$IMAGE_TAG
          docker service create --name service-auth --network $NETWORK_NAME --secret $SECRET_NAME_1 --secret $SECRET_NAME_2 --env-file .env --host $HOST_ALIAS:$HOST_IP --host $REDIS_HOST_ALIAS:$HOST_IP --publish $APP_PORT:$APP_PORT turistikrota/service.auth:$IMAGE_TAG
